default:
  image: node:14-buster
  before_script:
    - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")

stages:
  - install
  - build
  - test
  - deploy
  - release

install_dependencies:
  stage: install
  script:
    - npm install --unsafe-perm
  artifacts:
    paths:
      - node_modules

build_react_app:
  stage: build
  needs:
    - job: install_dependencies
      artifacts: true
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - build

build_electron_app:
  image: electronuserland/builder:wine
  stage: build
  needs:
    - job: install_dependencies
      artifacts: true
  script:
    - apt-get update
    - apt-get install xserver-xorg-dev libxi-dev libxext-dev -y
    - apt-get install xserver-xorg-dev:i386 libxi-dev:i386 libxext-dev:i386 -y
    - CI=false npm run electron-build
  artifacts:
    paths:
      - dist
  only:
    - release-desktop

test_app:
  stage: test
  script:
    - npm test

pages:
  stage: deploy
  needs:
    - job: build_react_app
      artifacts: true
  script:
    - ls -alh
    - rm -rf public
    - mkdir public
    - cp -r build/* public
  artifacts:
    paths:
      - public
  only:
    - release
    - release-desktop
