default:
  image: node:latest
  before_script:
    - NPM_PACKAGE_VERSION=$(node -p "require('./package.json').version")

stages:
  - install
  - build
  - test
  - deploy
  - release

install_dependencies:
  stage: install
  script:
    - npm install --unsafe-perm
  artifacts:
    paths:
      - node_modules

build_react_app:
  stage: build
  needs:
    - job: install_dependencies
      artifacts: true
  script:
    - npm run build
  artifacts:
    paths:
      - build

test_app:
  stage: test
  script:
    - npm test

pages:
  stage: deploy
  needs:
    - job: build_react_app
      artifacts: true
  script:
    - ls -alh
    - rm -rf public
    - mkdir public
    - cp -r build/* public
  artifacts:
    paths:
      - public
  only:
    - release
