name: deploy

on:
  push:
    branches:
      - stripped-release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: node_modules
        with:
          path: |
            node_modules/
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: Install deps
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          path: build/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Create branch stripped-dist
        run: |
          git checkout -b stripped-dist
          find . -mindepth 1 -maxdepth 1 -not -name .git -exec rm -rf {} +
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: .
      - name: Commit and push branch stripped-dist
        run: |
          git add .
          git commit -m "deploy: ${{ github.sha }}"
          git push --force origin stripped-dist:stripped-dist
